# Generated by Django 5.1.6 on 2025-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='access_token_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
