# Generated by Django 5.1.6 on 2025-03-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_club_created_at_club_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
