# Generated by Django 5.1.7 on 2025-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_match_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='template_pack',
            field=models.CharField(choices=[('classic', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal')], default='classic', max_length=50),
        ),
    ]
